services:
  - type: web
    name: news-retrieval-api
    env: docker
    repo: https://github.com/YOUR_GITHUB_USERNAME/YOUR_REPO_NAME # Change this
    branch: main # Or your deployment branch
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: news-db-supabase # Example name, configure in Render
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: news-cache-upstash # Example name, configure in Render
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false # Set this in Render's secret management
      - key: JWT_SECRET
        sync: false # Set this in Render's secret management
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    dockerCommand: npm run start
